let
    Source = Excel.Workbook(Web.Contents("(xy.xlsx in SharePoint)"), null, true),
    Tabelle1_Sheet = Source{[Item="Tabelle1",Kind="Sheet"]}[Data],
    #"Promoted Headers" = Table.PromoteHeaders(Tabelle1_Sheet, [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Calculation period", Int64.Type}, {"Calculation status", type text}, {"Sales organisation", Int64.Type}, {"Sales organisation name", type text}, {"Sales parent", type text}, {"Customer group", type text}, {"Mainstream material", type text}, {"Material", type text}, {"Material description", type text}, {"Currency sales price", type text}, {"Program", type text}, {"System", type text}, {"ORG+MAT", type text}, {"Budget Qty", type number}, {"Budget TO", type number}, {"Sales qty - prev. month", Int64.Type}, {"Turnover", type number}, {"Sales price", type number}, {"Material costs", type number}, {"Material costs EUR", type number}, {"Scrap", type number}, {"Scrap EUR", type number}, {"Mat OH", type number}, {"Mat OH EUR", type number}, {"3party", type number}, {"3party EUR", type number}, {"Machine costs", type number}, {"Machine costs EUR", type number}, {"Labour costs", type number}, {"Labour costs EUR", type number}, {"Setup_time cost", type number}, {"Setup costs EUR", type number}, {"Prod OH", type number}, {"Prod OH EUR", type number}, {"G&A OH", type number}, {"G&A OH EUR", type number}, {"Outbound OH", type number}, {"Outbound OH EUR", type number}, {"SG&A OH on mat", type number}, {"SG&A OH on mat EUR", type number}, {"SG&A OH on manuf", type number}, {"SG&A OH on manuf EUR", type number}, {"Total material EUR", type number}, {"Material ratio %", type number}, {"CM1 (p.unit)", type number}, {"CM2 (p.unit)", type number}, {"EBIT (p.unit)", type number}, {"CM1", type number}, {"CM2", type number}, {"EBIT", type number}, {"CM1 %", type number}, {"CM2 %", type number}, {"EBIT %", type number}}),
    #"Added Conditional Column" = Table.AddColumn(#"Changed Type", "Month", each if [Calculation period] = 1 then "January" else if [Calculation period] = 2 then "February" else if [Calculation period] = 3 then "March" else if [Calculation period] = 4 then "April" else if [Calculation period] = 5 then "May" else if [Calculation period] = 6 then "June" else if [Calculation period] = 7 then "July" else if [Calculation period] = 8 then "August" else if [Calculation period] = 9 then "September" else if [Calculation period] = 10 then "October" else if [Calculation period] = 11 then "November" else if [Calculation period] = 12 then "December" else "NOember"),
    #"Filtered empty&0 sales qtys" = Table.SelectRows(#"Added Conditional Column", each ([#"Sales qty - prev. month"] <> null and [#"Sales qty - prev. month"] <> 0)),
    #"Reordered Columns" = Table.ReorderColumns(#"Filtered empty&0 sales qtys",{"Calculation period", "Month", "Calculation status", "Sales organisation", "Sales organisation name", "Sales parent", "Customer group", "Mainstream material", "Material", "Material description", "Currency sales price", "Program", "System", "ORG+MAT", "Budget Qty", "Budget TO", "Sales qty - prev. month", "Turnover", "Sales price", "Material costs", "Material costs EUR", "Scrap", "Scrap EUR", "Mat OH", "Mat OH EUR", "3party", "3party EUR", "Machine costs", "Machine costs EUR", "Labour costs", "Labour costs EUR", "Setup_time cost", "Setup costs EUR", "Prod OH", "Prod OH EUR", "G&A OH", "G&A OH EUR", "Outbound OH", "Outbound OH EUR", "SG&A OH on mat", "SG&A OH on mat EUR", "SG&A OH on manuf", "SG&A OH on manuf EUR", "Total material EUR", "Material ratio %", "CM1 (p.unit)", "CM2 (p.unit)", "EBIT (p.unit)", "CM1", "CM2", "EBIT", "CM1 %", "CM2 %", "EBIT %"}),
    #"Filtered Rows" = Table.SelectRows(#"Reordered Columns", each true),
    #"Removed Columns" = Table.RemoveColumns(#"Filtered Rows",{"Material costs", "Scrap", "Mat OH", "3party", "Machine costs", "Labour costs", "Setup_time cost", "Prod OH"}),
    #"Removed Columns1" = Table.RemoveColumns(#"Removed Columns",{"G&A OH", "Outbound OH", "SG&A OH on mat", "SG&A OH on manuf"}),
    #"Filtered Rows1" = Table.SelectRows(#"Removed Columns1", each true),
    #"Replaced Value" = Table.ReplaceValue(#"Filtered Rows1",null,"Unknown",Replacer.ReplaceValue,{"Sales parent", "Customer group", "Program", "System"}),
    #"Merged Queries" = Table.NestedJoin(#"Replaced Value", {"Material"}, Project_Material_List, {"Material number"}, "Project_Material_List", JoinKind.LeftOuter),
    #"Expanded Project_Material_List" = Table.ExpandTableColumn(#"Merged Queries", "Project_Material_List", {"Projekt"}, {"Project_Material_List.Projekt"}),
    #"Renamed Columns" = Table.RenameColumns(#"Expanded Project_Material_List",{{"Project_Material_List.Projekt", "Project Number"}}),
    #"Added Material%" = Table.AddColumn(#"Renamed Columns", "Material%", each [#"Sales qty - prev. month"]*(([Material costs EUR]+[Scrap EUR]+[3party EUR]))/[Turnover]),
    #"Changed Type1" = Table.TransformColumnTypes(#"Added Material%",{{"Material%", Percentage.Type}}),
    #"Removed Errors" = Table.RemoveRowsWithErrors(#"Changed Type1", {"Material%"}),
    #"Added Labour%" = Table.AddColumn(#"Removed Errors", "Labour%", each [#"Sales qty - prev. month"]*[Labour costs EUR] / [Turnover]),
    #"Changed Type2" = Table.TransformColumnTypes(#"Added Labour%",{{"Labour%", Percentage.Type}}),
    #"Added Machines%" = Table.AddColumn(#"Changed Type2", "Machines%", each [#"Sales qty - prev. month"]*([Machine costs EUR]+[Setup costs EUR])/[Turnover]),
    #"Changed Type3" = Table.TransformColumnTypes(#"Added Machines%",{{"Machines%", Percentage.Type}}),
    #"Added Overhead%" = Table.AddColumn(#"Changed Type3", "Overhead%", each [#"Sales qty - prev. month"]*(([#"SG&A OH on mat EUR"]+[#"SG&A OH on manuf EUR"]+[Outbound OH EUR]+[#"G&A OH EUR"]+[Prod OH EUR]+[Mat OH EUR]))/[Turnover]),
    #"Changed Type4" = Table.TransformColumnTypes(#"Added Overhead%",{{"Overhead%", Percentage.Type}}),
    #"Replaced ProjectNum null to unknown" = Table.ReplaceValue(#"Changed Type4",null,"Unknown",Replacer.ReplaceValue,{"Project Number"}),
    #"New ID column" = Table.AddColumn(#"Replaced ProjectNum null to unknown", "ID", each Text.Combine({[#"ORG+MAT"], Text.From([Year], "hu-HU"), Text.From([Calculation period], "hu-HU")}, "-"), type text),
    #"Removed Duplicates" = Table.Distinct(#"New ID column", {"ID"})
in
    #"Removed Duplicates"
